### PR TITLE
Allow All CORS preflight requests

### PR DESCRIPTION
**Pull request by rvantonder**
- Uses the `cors` package to allow all CORS origins 
- Adds `app.options('*', cors())` to allow all origins in CORS preflight requests

Addresses #91

### CODE REVIEW

**Comment by rvantonder** [comment]
Tested this with:

Before:
```
$ curl -i -X OPTIONS localhost:3000                                                                                                                                             

HTTP/1.1 200 OK
X-Powered-By: Express
Allow: GET,HEAD
Content-Type: text/html; charset=utf-8
Content-Length: 8
ETag: W/"8-ZRAf8oNBS3Bjb/SU2GYZCmbtmXg"
Date: Tue, 18 Dec 2018 22:42:29 GMT
Connection: keep-alive

GET,HEAD
```

After:
```
$ curl -i -X OPTIONS localhost:3000                                                                                                                                             

HTTP/1.1 204 No Content
X-Powered-By: Express
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET,HEAD,PUT,PATCH,POST,DELETE
Vary: Access-Control-Request-Headers
Content-Length: 0
Date: Tue, 18 Dec 2018 22:47:03 GMT
Connection: keep-alive
```

I'm not too familiar with existing code/tests; happy to take suggestions for improving this, or tests can be added by core maintainers.

**Comment by rvantonder** [comment]
Ping on this PR, any chance we can allow these requests? (maybe @tcbyrd or @JasonEtco?)

**Comment by JasonEtco** [comment]
Hi @rvantonder - sorry that this fell off our radar 🙏 PR looks fine to me, I'd like to get a more informed opinion about the security impact of this. I'll ask around/do some research just to double check, but it _should_ be fine! Will report back soon.

**Comment by rvantonder** [comment]
Sure thing! There's some more detail in #91. My understanding is that since smee is set up to allow all origins [anyway](https://github.com/probot/smee/blob/master/server/server.js#L82), this doesn't impact the security policy. The changes allow applications that expect a response to preflight requests to continue with the connection. Currently there are applications that will drop the connection if the preflight requests don't get a response with those headers (meaning smee can't be used). But yes, double check :)

**Comment by JasonEtco** [comment]
@rvantonder - this is still on my radar, just wanted to let you know that we're doing a larger security review so this'll have to stay open as a part of that. Will let you know if we have any questions!

**Comment by JasonEtco** [comment]
My apparently monthly update that this hasn't been forgotten about - like I said, we're working with our (GitHub's) security team for a full review of Smee, including this. We're making progress but nothing to share just yet ✨ thanks for your continued patience 🙏

**Pull request closed without merging**
