### PR TITLE
refactor: modernize code and remove dependencies

### PR DESCRIPTION
**Pull request by Uzlopak**
This PR refactors the whole codebase. Removes unecessary deps, use of built in fetch. 

Should be released as semver-major.

I was first confused, because it seemed, that it was bugged, because the payload of the endpoint was not returned. Then I tested it with the original smee-client and realized that it is a one way thing... smee.io does not return the answer of the webserver. Please correct me if I am wrong. 

Coverage is improved significantly.

```sh
 % Coverage report from v8
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |   94.49 |    88.88 |   66.66 |   94.49 |                   
 index.ts |   94.49 |    88.88 |   66.66 |   94.49 | 80-81,85-86,89-90 
----------|---------|----------|---------|---------|-------------------
```

BREAKING CHANGE: drop support for Node <18

BREAKING CHANGE: use native `fetch` for requests

### CODE REVIEW

**Comment by Uzlopak** [comment]
@gr2m 
@wolfy1339

**Review by gr2m — APPROVED** [review]
What are the breaking changes? Drop support for Node < 18 and use of native fetch?

**Comment by Uzlopak** [comment]
exactly

**Comment by Uzlopak** [comment]
Can I get permissions please? I could then close some issues and pull requests, when this gets released.

**Review by wolfy1339 — APPROVED** [review]

**Comment by Uzlopak** [comment]
@gr2m 
Thanks for the permissions

**Comment by gr2m** [comment]
we don't have an automated release setup yet, let me take care of this

**Comment by gr2m** [comment]
well ouch that should have been v2.0.0 not sure why it didn't recognize the

```
BREAKING CHANGE: drop support for Node <18

BREAKING CHANGE: use native fetch for requests
```

I'm looking into it

**Comment by gr2m** [comment]
lol now the revert failed to build: https://github.com/probot/smee-client/actions/runs/6909425601/job/18800742387 so I cannot release 1.2.5 🤷🏼 

For now I've set 1.2.3 as `latest` on npm.

**Comment by gr2m** [comment]
@Uzlopak do these type errors look familiar? Maybe they are easy to fix in the 1.x branch?

```
> tsc -p tsconfig.json

node_modules/@types/eventsource/dom-monkeypatch.d.ts:42:14 - error TS2717: Subsequent property declarations must have the same type.  Property 'AT_TARGET' must be of type 'number', but here has type '2'.

42     readonly AT_TARGET: 2;
                ~~~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:5221:14
    5221     readonly AT_TARGET: number;
                      ~~~~~~~~~
    'AT_TARGET' was also declared here.

node_modules/@types/eventsource/dom-monkeypatch.d.ts:43:14 - error TS2717: Subsequent property declarations must have the same type.  Property 'BUBBLING_PHASE' must be of type 'number', but here has type '3'.

43     readonly BUBBLING_PHASE: 3;
                ~~~~~~~~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:5222:14
    5222     readonly BUBBLING_PHASE: number;
                      ~~~~~~~~~~~~~~
    'BUBBLING_PHASE' was also declared here.

node_modules/@types/eventsource/dom-monkeypatch.d.ts:44:14 - error TS2717: Subsequent property declarations must have the same type.  Property 'CAPTURING_PHASE' must be of type 'number', but here has type '1'.

44     readonly CAPTURING_PHASE: 1;
                ~~~~~~~~~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:5223:14
    5223     readonly CAPTURING_PHASE: number;
                      ~~~~~~~~~~~~~~~
    'CAPTURING_PHASE' was also declared here.

node_modules/@types/eventsource/dom-monkeypatch.d.ts:45:14 - error TS2717: Subsequent property declarations must have the same type.  Property 'NONE' must be of type 'number', but here has type '0'.

45     readonly NONE: 0;
                ~~~~

  node_modules/typescript/lib/lib.dom.d.ts:5224:14
    5224     readonly NONE: number;
                      ~~~~
    'NONE' was also declared here.
```

**Comment by gr2m** [comment]
I might have found a way

**Comment by gr2m** [comment]
All set.

**Pull request merged**
